# Generated by Django 4.2.26 on 2025-11-24 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('pais_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca de Vehículo',
                'verbose_name_plural': 'Marcas de Vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=26, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('monto', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado'), ('listo_retiro', 'Listo para Retiro'), ('retirado', 'Retirado'), ('preparacion', 'En Preparación'), ('enviado', 'Enviado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('webpay', 'WebPay'), ('transferencia', 'Transferencia Bancaria')], default='webpay', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('retiro_en_tienda', models.BooleanField(default=False)),
                ('envio_domicilio', models.BooleanField(default=False)),
                ('direccion', models.CharField(blank=True, max_length=225, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_comuna_chilexpress', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_total', models.FloatField(blank=True, null=True)),
                ('alto', models.PositiveIntegerField(blank=True, null=True)),
                ('ancho', models.PositiveIntegerField(blank=True, null=True)),
                ('largo', models.PositiveIntegerField(blank=True, null=True)),
                ('costo_envio', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ot_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('etiqueta_url', models.URLField(blank=True, null=True)),
                ('estado_envio', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField(default=1)),
                ('precio_mayorista', models.PositiveIntegerField(default=1)),
                ('descripcion', models.CharField(max_length=500)),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('largo', models.PositiveIntegerField()),
                ('ancho', models.PositiveIntegerField()),
                ('alto', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.categoria')),
                ('marca', models.ManyToManyField(related_name='productos', to='tienda.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_auto', models.CharField(max_length=100)),
                ('año_desde', models.IntegerField()),
                ('año_hasta', models.IntegerField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.marca')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador', models.BooleanField(default=False)),
                ('empresa', models.BooleanField(default=False)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rut', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('año_inicio', models.IntegerField()),
                ('año_fin', models.IntegerField(blank=True, null=True)),
                ('tipo_vehiculo', models.CharField(choices=[('sedan', 'Sedán'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('pickup', 'Pick-up'), ('coupe', 'Coupé'), ('convertible', 'Convertible'), ('wagon', 'Station Wagon'), ('minivan', 'Minivan'), ('otro', 'Otro')], default='sedan', max_length=50)),
                ('cilindrada', models.CharField(blank=True, max_length=20, null=True)),
                ('combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('hibrido', 'Híbrido'), ('electrico', 'Eléctrico'), ('gnv', 'GNV'), ('otro', 'Otro')], default='gasolina', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('marca_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='tienda.marcavehiculo')),
            ],
            options={
                'verbose_name': 'Modelo de Vehículo',
                'verbose_name_plural': 'Modelos de Vehículos',
                'ordering': ['marca_vehiculo__nombre', 'nombre', 'año_inicio'],
                'unique_together': {('marca_vehiculo', 'nombre', 'año_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.IntegerField(choices=[(33, 'Factura Electrónica'), (39, 'Boleta Electrónica'), (56, 'Nota de Débito Electrónica'), (61, 'Nota de Crédito Electrónica')], default=39)),
                ('numero_factura', models.CharField(blank=True, max_length=20, null=True)),
                ('folio', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('rut_cliente', models.CharField(default='66666666-6', max_length=12)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('direccion_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('neto', models.PositiveIntegerField()),
                ('iva', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generada', 'Generada'), ('enviada_sii', 'Enviada al SII'), ('aceptada_sii', 'Aceptada por SII'), ('rechazada_sii', 'Rechazada por SII'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('xml_url', models.URLField(blank=True, null=True)),
                ('tributi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_sii', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='tienda.pedido')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CompatibilidadVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_desde', models.IntegerField(blank=True, null=True)),
                ('año_hasta', models.IntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la compatibilidad', null=True)),
                ('verificado', models.BooleanField(default=False, help_text='Compatibilidad verificada por técnico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('todas', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modelo_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.modelovehiculo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Compatibilidad de Vehículo',
                'verbose_name_plural': 'Compatibilidades de Vehículos',
                'ordering': ['producto__nombre', 'modelo_vehiculo__marca_vehiculo__nombre'],
                'unique_together': {('producto', 'modelo_vehiculo', 'año_desde', 'año_hasta')},
            },
        ),
    ]
